tabuada = 2;
    function escreva(){
document.write(tabuada + "x 1 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 2 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 3 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 4 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 5 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 6 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 7 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 8 =" + (tabuada)); + "<br>"
document.write(tabuada + "x 9 =" + (tabuada)); + "<br>"

}

function minhatabuada(){
for(let i = 1; i <10; i++)
for(let j = 1; j <10 j++)

 document.write(i +"x 5 + =" + j + "=" +(j+i)+ "<br>");
 document.write("<br>");
}
function cubo(){
for(let i =2; i = <=6; i++){
document.write("o cubo de" + i + " é "+i "x" + i "x" i "="(i+i+i+i))


}
}